import { test, expect } from '@playwright/test';
test('play, inspect, govern, save, reload, and complete a mandate', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message));
  await page.goto('/');
  await expect(page.getByRole('heading', { name: 'A country in your hands.' })).toBeVisible();
  await page.screenshot({ path: 'test-results/commonwealth-desktop.png', fullPage: true });
  await page.getByLabel('Select a region').selectOption('1');
  await expect(page.locator('.inspector h2')).toContainText('mapxels selected');
  await page.getByRole('button', { name: 'Food access', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Food access', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await page.getByRole('button', { name: 'Next month' }).click();
  await expect(page.locator('.date strong')).toHaveText('Feb 2032');
  await page.getByRole('button', { name: 'Console', exact: true }).click();
  await page.getByLabel('Government command').fill('subsidize sports 1.5 in selected');
  await page.getByRole('button', { name: 'Preview command' }).click();
  await expect(page.getByRole('dialog')).toContainText('₡1.50');
  await page.getByRole('button', { name: 'Enact measure →', exact: true }).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.getByRole('tab', { name: /The daily ledger/ }).click();
  await expect(page.locator('.news-card').first()).toContainText('sports subsidy');
  await page.locator('.news-card').first().getByRole('button', { name: 'Follow the causes' }).click();
  await expect(page.getByRole('dialog')).toContainText('Your decision');
  await page.getByRole('button', { name: 'Close dialog' }).click();
  await page.reload();
  await expect(page.locator('.date strong')).toHaveText('Feb 2032');
  await page.getByRole('button', { name: 'Save & load' }).click();
  const downloaded = page.waitForEvent('download'); await page.getByRole('button', { name: 'Export save' }).click();
  const backup = await downloaded;
  expect(backup.suggestedFilename()).toBe('commonwealth-month-1.json');
  await page.getByRole('button', { name: 'Close dialog' }).click();
  for (let tick = 1; tick < 48; tick++) await page.getByRole('button', { name: 'Next month' }).click();
  await expect(page.getByRole('dialog')).toContainText('The country you leave behind');
  await expect(page.getByRole('dialog')).toContainText('48 months');
  await expect(page.locator('.report-voices blockquote')).toHaveCount(3);
  await page.screenshot({ path: 'test-results/commonwealth-mandate.png', fullPage: true });
  await page.getByRole('button', { name: 'Close dialog' }).click();
  await expect(page.getByRole('button', { name: 'Next month' })).toBeDisabled();
  await page.reload();
  await expect(page.getByRole('button', { name: 'Next month' })).toBeDisabled();
  await expect(page.locator('.date strong')).toHaveText('Jan 2036');
  await page.getByRole('button', { name: 'Save & load' }).click();
  await page.locator('#import-save').setInputFiles((await backup.path())!);
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await expect(page.locator('.date strong')).toHaveText('Feb 2032');
  await expect(page.getByRole('button', { name: 'Next month' })).toBeEnabled();
  expect(errors).toEqual([]);
});
test('mobile layout, map click, invalid commands and imports, and a fresh country', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 }); await page.goto('/');
  await page.screenshot({ path: 'test-results/commonwealth-mobile.png', fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);
  const map = page.locator('#map'); const box = (await map.boundingBox())!;
  await map.click({ position: { x: box.width / 2, y: box.height / 2 } });
  await expect(page.locator('.inspector-description')).toContainText('Mapxel');
  await page.getByRole('button', { name: 'Console', exact: true }).click();
  await page.getByLabel('Government command').fill('tax income 99');
  await page.getByRole('button', { name: 'Preview command' }).click();
  await expect(page.getByRole('status')).toContainText('finite number');
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.getByRole('button', { name: 'Save & load' }).click();
  await page.locator('#import-save').setInputFiles({ name: 'bad.json', mimeType: 'application/json', buffer: Buffer.from('{"version":999}') });
  await expect(page.locator('#import-error')).toContainText('unsupported');
  await page.getByRole('button', { name: 'Close dialog' }).click();
  await expect(page.locator('.date strong')).toHaveText('Jan 2032');
  await page.setViewportSize({ width: 1280, height: 900 });
  await page.getByRole('button', { name: 'New country' }).click();
  await page.getByLabel('Country seed').fill('test-new-country');
  await page.getByRole('button', { name: 'Begin a new mandate' }).click();
  await expect(page.locator('footer')).toContainText('test-new-country');
});
test('the wage floor can be enacted and survives the browser autosave', async ({ page }) => {
  await page.goto('/');
  await page.locator('#wage-form input[name="amount"]').fill('8');
  await page.locator('#wage-form button').click();
  await expect(page.getByRole('dialog')).toContainText('₡8.00 per worker');
  await page.getByRole('button', { name: 'Enact measure →', exact: true }).click();
  await page.getByRole('button', { name: 'Next month' }).click();
  await page.reload();
  await expect(page.locator('#wage-form input[name="amount"]')).toHaveValue('8');
});
